export const purchaseReceiveConfig = [
  {
    label: "PO",
    width: "175",
    sortable: true,
    prop: "id",
  },
  {
    label: "Order Id",
    width: "120",
    sortable: true,
    prop: "order_id",
  },
  {
    label: "Manufacturer",
    width: "155",
    sortable: true,
    prop: "manufacturer",
  },
  {
    label: "Ordered Date",
    width: "145",
    sortable: true,
    prop: "ordered_date",
  },
  {
    label: "Ordered QTY",
    width: "160",
    sortable: true,
    prop: "ordered_qyt",
  },
  {
    label: "Batch No.",
    width: "150",
    sortable: true,
    prop: "batch_num",
    popover: true,
  },
  {
    label: "RECEIVED QTY",
    width: "160",
    sortable: true,
    prop: "received_qyt",
  },
  {
    label: "Received Date",
    width: "160",
    sortable: true,
    prop: "received_date",
  },
  {
    label: "RECEIVED QTY",
    width: "160",
    sortable: true,
    prop: "received_qyt",
  },
  {
    label: "Total Value",
    width: "160",
    sortable: true,
    prop: "total_value",
  },
  {
    label: "Testing",
    width: "155",
    sortable: true,
    prop: "testing",
  },
  {
    label: "Invoice",
    width: "130",
    sortable: true,
    prop: "invoice",
  },
];

export const purchaseReceive = {
  items: [
    {
      id: 101,
      order_id: "#A1234",
      manufacturer: "Mg gas ltd",
      ordered_date: "2023-01-01",
      ordered_qyt: "1000",
      batch_num: "A01",
      received_qyt: "3000",
      received_date: "2023-01-01",
      total_value: "GHs 15000",
      testing: "Not",
      invoice: 104,
      children: [
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        },
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        }
      ]
    },
    {
      id: 102,
      order_id: "#A1234",
      manufacturer: "Mg gas ltd",
      ordered_date: "2023-01-01",
      ordered_qyt: "1000",
      batch_num: "A01",
      received_qyt: "3000",
      received_date: "2023-01-01",
      total_value: "GHs 15000",
      testing: "Not",
      invoice: 104,
      children: [
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        },
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        }
      ]
    },
    {
      id: 103,
      order_id: "#A1234",
      manufacturer: "Mg gas ltd",
      ordered_date: "2023-01-01",
      ordered_qyt: "1000",
      batch_num: "A01",
      received_qyt: "3000",
      received_date: "2023-01-01",
      total_value: "GHs 15000",
      testing: "Not",
      invoice: 104,
      children: [
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        },
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        }
      ]
    },
    {
      id: 104,
      order_id: "#A1234",
      manufacturer: "Mg gas ltd",
      ordered_date: "2023-01-01",
      ordered_qyt: "1000",
      batch_num: "A01",
      received_qyt: "3000",
      received_date: "2023-01-01",
      total_value: "GHs 15000",
      testing: "Not",
      invoice: 104,
      children: [
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        },
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        }
      ]
    },
    {
      id: 105,
      order_id: "#A1234",
      manufacturer: "Mg gas ltd",
      ordered_date: "2023-01-01",
      ordered_qyt: "1000",
      batch_num: "A01",
      received_qyt: "3000",
      received_date: "2023-01-01",
      total_value: "GHs 15000",
      testing: "Not",
      invoice: 104,
      children: [
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        },
        {
          id: "-",
          order_id: "-",
          manufacturer: "-",
          ordered_date: "-",
          ordered_qyt: "-",
          batch_num: "A012",
          received_qyt: "3000",
          received_date: "2023-01-01",
          total_value: "GHs 15000",
          testing: "Done",
          invoice: "-",
        }
      ]
    },
  ],
  page: 1,
  pages: 1,
  size: 10,
  total: 60,
};

export const cylinderTrackConfig = [
  {
    label: "Cylinder ID",
    width: "150",
    sortable: true,
    prop: "id",
    popover: true,
  },
  {
    label: "product",
    width: "175",
    sortable: true,
    prop: "product",
  },
  {
    label: "Condition Status",
    width: "175",
    sortable: true,
    prop: "condition_status",
  },
  {
    label: "Ownership Status",
    width: "200",
    sortable: true,
    prop: "owner_status",
  },
  {
    label: "Ownership Person",
    width: "160",
    sortable: true,
    prop: "owner_person",
  },
  {
    label: "CYLINDER Location",
    width: "160",
    sortable: true,
    prop: "cylinder_loc",
  },
];

export const cylinderTrack = {
  items: [
    {
      id: "N02231010000002",
      product: "3kg | steel",
      condition_status: "Mg gas ltd",
      owner_status: "Distributor",
      owner_person: "Yaw Graham",
      cylinder_loc: "Atomic GS-0757-3391",
    },
    {
      id: "N02231010000002",
      product: "3kg | steel",
      condition_status: "Mg gas ltd",
      owner_status: "Distributor",
      owner_person: "Yaw Graham",
      cylinder_loc: "Atomic GS-0757-3391",
    },
    {
      id: "N02231010000002",
      product: "3kg | steel",
      condition_status: "Mg gas ltd",
      owner_status: "Distributor",
      owner_person: "Yaw Graham",
      cylinder_loc: "Atomic GS-0757-3391",
    },
    {
      id: "N02231010000002",
      product: "3kg | steel",
      condition_status: "Mg gas ltd",
      owner_status: "Distributor",
      owner_person: "Yaw Graham",
      cylinder_loc: "Atomic GS-0757-3391",
    },
    {
      id: "N02231010000002",
      product: "3kg | steel",
      condition_status: "Mg gas ltd",
      owner_status: "Distributor",
      owner_person: "Yaw Graham",
      cylinder_loc: "Atomic GS-0757-3391",
    },
  ],
};

export const distributorStockConfig = [
  {
    label: "Id",
    width: "75",
    sortable: true,
    prop: "id",
    popover: true,
  },
  {
    label: "Distributor Name",
    width: "175",
    sortable: true,
    prop: "distributor_name",
  },
  {
    label: "Zone",
    width: "150",
    sortable: true,
    prop: "zone",
  },
  {
    label: "Email",
    width: "120",
    sortable: true,
    prop: "email",
  },
  {
    label: "Phone",
    width: "150",
    sortable: true,
    prop: "phone",
  },
  {
    label: "Storage Capacity",
    width: "150",
    sortable: true,
    prop: "storage_cap",
  },
];

export const distributorStock = {
  items: [
    {
      id: 101,
      distributor_name: [
        {
          content: "Yaw Graham",
          url: "https://d2v5dzhdg4zhx3.cloudfront.net/web-assets/images/storypages/short/linkedin-profile-picture-maker/dummy_image/thumb/004.webp",
        },
      ],
      zone: "Northern",
      email: "abc123@xyz.com",
      phone: " 0277400000",
      storage_cap: "10,000",
    },
    {
      id: 101,
      distributor_name: [
        {
          content: "Yaw Graham",
          url: "https://d2v5dzhdg4zhx3.cloudfront.net/web-assets/images/storypages/short/linkedin-profile-picture-maker/dummy_image/thumb/004.webp",
        },
      ],
      zone: "Northern",
      email: "abc123@xyz.com",
      phone: " 0277400000",
      storage_cap: "10,000",
    },
    {
      id: 101,
      distributor_name: [
        {
          content: "Yaw Graham",
          url: "https://d2v5dzhdg4zhx3.cloudfront.net/web-assets/images/storypages/short/linkedin-profile-picture-maker/dummy_image/thumb/004.webp",
        },
      ],
      zone: "Northern",
      email: "abc123@xyz.com",
      phone: " 0277400000",
      storage_cap: "10,000",
    },
    {
      id: 101,
      distributor_name: [
        {
          content: "Yaw Graham",
          url: "https://d2v5dzhdg4zhx3.cloudfront.net/web-assets/images/storypages/short/linkedin-profile-picture-maker/dummy_image/thumb/004.webp",
        },
      ],
      zone: "Northern",
      email: "abc123@xyz.com",
      phone: " 0277400000",
      storage_cap: "10,000",
    },
    {
      id: 101,
      distributor_name: [
        {
          content: "Yaw Graham",
          url: "https://d2v5dzhdg4zhx3.cloudfront.net/web-assets/images/storypages/short/linkedin-profile-picture-maker/dummy_image/thumb/004.webp",
        },
      ],
      zone: "Northern",
      email: "abc123@xyz.com",
      phone: " 0277400000",
      storage_cap: "10,000",
    },
    {
      id: 101,
      distributor_name: [
        {
          content: "Yaw Graham",
          url: "https://d2v5dzhdg4zhx3.cloudfront.net/web-assets/images/storypages/short/linkedin-profile-picture-maker/dummy_image/thumb/004.webp",
        },
      ],
      zone: "Northern",
      email: "abc123@xyz.com",
      phone: " 0277400000",
      storage_cap: "10,000",
    },
  ],
};
